#!/bin/bash

# Autonomous Marketeer Setup Script
# This script initializes the environment for first-time setup

echo "========================================="
echo "  Autonomous Marketeer - Setup"
echo "========================================="
echo ""

# Check if .env exists
if [ ! -f .env ]; then
    echo "[*] Creating .env file from .env.example..."
    cp .env.example .env
    echo "    .env file created successfully!"
else
    echo "[*] .env file already exists"
fi

echo ""
echo "========================================="
echo "  Configuration"
echo "========================================="
echo ""
echo "The system is configured with the following defaults:"
echo ""
echo "  LLM Provider: OpenAI (requires API key)"
echo "  API Gateway:  http://localhost:8080"
echo "  Dashboard:    http://localhost:5173"
echo "  Analytics:    http://localhost:8086"
echo "  Attribution:  http://localhost:8085"
echo ""
echo "Default Login:"
echo "  Email:    admin@demo.com"
echo "  Password: demo123"
echo ""
echo "========================================="
echo "  IMPORTANT: Add Your OpenAI API Key"
echo "========================================="
echo ""
echo "Before starting, edit .env and add your OpenAI API key:"
echo ""
echo "  nano .env"
echo ""
echo "Find this line:"
echo "  OPENAI_API_KEY=sk-your-openai-key-here"
echo ""
echo "Replace with your actual API key from:"
echo "  https://platform.openai.com/api-keys"
echo ""
echo "========================================="
echo "  Alternative: Use Local LLM (Advanced)"
echo "========================================="
echo ""
echo "To use local LLM (requires 16GB+ RAM):"
echo "  1. Edit .env"
echo "  2. Set LOCAL_LLM_ENABLED=true"
echo "  3. Set LLM_PROVIDER=local"
echo "  4. Set OPENAI_ENABLED=false"
echo ""
echo "First startup will be slow (model download)"
echo ""
echo "========================================="
echo "  Starting Services"
echo "========================================="
echo ""
echo "Run the following command to start all services:"
echo ""
echo "  docker-compose up --build"
echo ""
echo "Or in detached mode:"
echo ""
echo "  docker-compose up -d --build"
echo ""
echo "========================================="
echo "  Setup Complete!"
echo "========================================="
echo ""
